language: elixir
elixir:
  - 1.7.4
sudo: false
cache: false
env:
  TRAVISCICONEJO=true
notifications:
  recipients:
    - iam@mendrugory.com
otp_release:
  - 21.0
services:
  - docker
before_install:
- docker pull rabbitmq:3-management
- docker run -d -p 127.0.0.1:5672:5672 --name rabbitmq rabbitmq:3-management
script: mix test --no-start --trace